import { useMemo, useRef, useState } from "react";
import { createPortal } from "react-dom";
import Button from "../../components/common/Button";
import Card from "../../components/common/Card";
import { resolvePackageImageUrl } from "../../services/photographyPackagesService";

const emptyPackage = { name: "", description: "", basePrice: "", extraHourRate: 0, additionalPhotographerRate: 0, durationHours: "", numberOfPhotographers: 1, editedPhotoCount: 0, albumIncluded: false, videoIncluded: false, status: "Active", serviceIds: [], coverImage: null };
const emptyAddon = { name: "", description: "", price: "" };
const money = new Intl.NumberFormat("en-LK", { style: "currency", currency: "LKR" });

function Modal({ title, children, className = "" }) {
  return createPortal(<div className="studio-modal-backdrop"><div className={`studio-modal ${className}`} role="dialog" aria-modal="true" aria-labelledby="package-modal-title"><div className="studio-modal-heading"><h3 id="package-modal-title">{title}</h3></div>{children}</div></div>, document.body);
}
function Facts({ item }) {
  return <dl className="package-facts"><div><dt>Duration</dt><dd>{item.durationHours} hours</dd></div><div><dt>Photographers</dt><dd>{item.numberOfPhotographers}</dd></div><div><dt>Edited photos</dt><dd>{item.editedPhotoCount}</dd></div><div><dt>Album</dt><dd>{item.albumIncluded ? "Yes" : "No"}</dd></div><div><dt>Video</dt><dd>{item.videoIncluded ? "Yes" : "No"}</dd></div></dl>;
}
function IncludedServices({ services = [], compact = false }) {
  if (!services.length) return <p className="package-no-services">No services included.</p>;
  const visible = compact ? services.slice(0, 3) : services;
  return <ul className="package-service-list">{visible.map((service) => <li key={service.id}>{service.serviceName}</li>)}{compact && services.length > visible.length && <li>+{services.length - visible.length} more</li>}</ul>;
}
function AddonList({ addons, onEdit, onDelete }) {
  return addons.length ? <div className="addon-list">{addons.map((addon) => <div className="addon-row" key={addon.id}><div><strong>{addon.name}</strong><p>{addon.description || "No description provided."}</p></div><div className="addon-row-end"><strong>{money.format(addon.price)}</strong><div><button type="button" onClick={() => onEdit(addon)}>Edit</button><button type="button" className="danger-action" onClick={() => onDelete(addon)}>Delete</button></div></div></div>)}</div> : <p className="package-picker-message">No add-ons have been created for this package.</p>;
}
export default function StudioPackages({ packages, services, servicesLoading, servicesError, packagesLoading, error, onRetry, onCreate, onUpdate, onDelete, onLoadAddons, onCreateAddon, onUpdateAddon, onDeleteAddon }) {
  const [editor, setEditor] = useState(undefined), [form, setForm] = useState(emptyPackage), [viewing, setViewing] = useState(null), [deleting, setDeleting] = useState(null), [search, setSearch] = useState(""), [status, setStatus] = useState(""), [sort, setSort] = useState("newest"), [saving, setSaving] = useState(false), [feedback, setFeedback] = useState(""), [validation, setValidation] = useState({});
  const [addonPanel, setAddonPanel] = useState(null), [addons, setAddons] = useState([]), [addonsLoading, setAddonsLoading] = useState(false), [addonForm, setAddonForm] = useState(emptyAddon), [addonEditor, setAddonEditor] = useState(null), [addonSaving, setAddonSaving] = useState(false), [addonDeleting, setAddonDeleting] = useState(null), [addonError, setAddonError] = useState("");
  const filtered = useMemo(() => packages.filter((item) => (!search || `${item.name} ${item.description}`.toLowerCase().includes(search.toLowerCase())) && (!status || item.status === status)).sort((a, b) => sort === "price-asc" ? a.basePrice - b.basePrice : sort === "price-desc" ? b.basePrice - a.basePrice : sort === "name" ? a.name.localeCompare(b.name) : new Date(b.createdAt) - new Date(a.createdAt)), [packages, search, status, sort]);
  const openEditor = (item) => { setEditor(item || null); setForm(item ? { ...item, extraHourRate: item.extraHourRate ?? 0, additionalPhotographerRate: item.additionalPhotographerRate ?? 0, serviceIds: (item.services || []).map((service) => service.id), coverImage: null } : { ...emptyPackage }); setValidation({}); };
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const toggleService = (id) => update("serviceIds", form.serviceIds.includes(id) ? form.serviceIds.filter((serviceId) => serviceId !== id) : [...form.serviceIds, id]);
  const validate = () => { const next = {}; if (!form.name.trim()) next.name = "Package name is required."; if (!(Number(form.basePrice) > 0)) next.basePrice = "Price must be greater than zero."; if (Number(form.extraHourRate) < 0) next.extraHourRate = "Rate cannot be negative."; if (Number(form.additionalPhotographerRate) < 0) next.additionalPhotographerRate = "Rate cannot be negative."; if (!(Number(form.durationHours) > 0)) next.durationHours = "Duration must be greater than zero."; if (!(Number(form.numberOfPhotographers) > 0)) next.numberOfPhotographers = "Photographers must be greater than zero."; if (Number(form.editedPhotoCount) < 0 || form.editedPhotoCount === "") next.editedPhotoCount = "Edited photos cannot be negative."; if (!form.serviceIds.length) next.serviceIds = "Select at least one included service."; setValidation(next); return !Object.keys(next).length; };
  const submit = async (event) => { event.preventDefault(); if (!validate()) return; setSaving(true); try { if (editor) await onUpdate(editor.id, form); else await onCreate(form); setEditor(undefined); setFeedback(editor ? "Package updated successfully." : "Package created successfully."); } catch (failure) { setFeedback(failure.message || "Unable to save package."); } finally { setSaving(false); } };
  const addonSession = useRef(0);
  const resetAddons = () => { setAddons([]); setAddonForm(emptyAddon); setAddonEditor(null); setAddonDeleting(null); setAddonError(""); setAddonSaving(false); setAddonsLoading(false); };
  const closeAddons = () => { addonSession.current++; setAddonPanel(null); resetAddons(); };
  const loadAddons = async (item) => {
    const session = ++addonSession.current;
    resetAddons(); setAddonPanel(item); setAddonsLoading(true);
    try { const loaded = await onLoadAddons(item.id); if (session === addonSession.current) setAddons(loaded); }
    catch (failure) { if (session === addonSession.current) setAddonError(failure.message || "Unable to load add-ons."); }
    finally { if (session === addonSession.current) setAddonsLoading(false); }
  };
  const saveAddon = async (event) => {
    event.preventDefault();
    if (!addonPanel || addonsLoading || addonSaving) return;
    const price = Number(addonForm.price);
    if (!addonForm.name.trim() || addonForm.price === "" || !Number.isFinite(price) || price < 0) { setAddonError("Enter a valid name and a price of zero or greater."); return; }
    const session = addonSession.current, packageId = addonPanel.id, editingId = addonEditor?.id;
    setAddonSaving(true);
    try {
      const values = { ...addonForm, price };
      const saved = editingId ? await onUpdateAddon(packageId, editingId, values) : await onCreateAddon(packageId, values);
      if (session !== addonSession.current) return;
      setAddons((current) => editingId ? current.map((item) => item.id === editingId ? saved : item) : [...current, saved].sort((a, b) => a.name.localeCompare(b.name)));
      setAddonEditor(null); setAddonForm(emptyAddon); setAddonError("");
    } catch (failure) { if (session === addonSession.current) setAddonError(failure.message || "Unable to save add-on."); }
    finally { if (session === addonSession.current) setAddonSaving(false); }
  };
  const deleteAddon = async () => {
    if (!addonPanel || !addonDeleting) return;
    const session = addonSession.current, packageId = addonPanel.id, addonId = addonDeleting.id;
    try { await onDeleteAddon(packageId, addonId); if (session !== addonSession.current) return; setAddons((current) => current.filter((item) => item.id !== addonId)); setAddonDeleting(null); }
    catch (failure) { if (session === addonSession.current) setAddonError(failure.message || "Unable to delete add-on."); }
  };
  const field = (key, label, type = "text", extra = {}) => <label className="profile-field"><span>{label}</span><input type={type} value={form[key]} onChange={(event) => update(key, event.target.value)} {...extra} />{validation[key] && <small className="field-error">{validation[key]}</small>}</label>;
  const servicePicker = servicesLoading ? <p className="package-picker-message">Loading services...</p> : servicesError ? <p className="package-picker-message field-error">{servicesError}</p> : services.length ? <div className="package-services-picker">{services.map((service) => <label key={service.id}><input type="checkbox" checked={form.serviceIds.includes(service.id)} onChange={() => toggleService(service.id)} /> <span>{service.serviceName}</span></label>)}</div> : <p className="package-picker-message">No services available. <a href="/studio/services">Create services first.</a></p>;
  return <section className="studio-section" aria-labelledby="packages-title"><div className="section-heading"><div><p className="studio-kicker">PACKAGE MANAGEMENT</p><h2 id="packages-title">Packages</h2><p>Create and manage photography packages for your studio.</p></div><Button onClick={() => openEditor(null)}>Add Package</Button></div>{packages.length > 0 && <div className="management-controls packages-controls"><label className="management-search"><span>⌕</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search packages..." /></label><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">All statuses</option><option>Active</option><option>Inactive</option></select><select value={sort} onChange={(event) => setSort(event.target.value)}><option value="newest">Newest first</option><option value="price-asc">Price: Low to High</option><option value="price-desc">Price: High to Low</option><option value="name">Name: A-Z</option></select></div>}{feedback && <p className="portfolio-feedback success">{feedback}</p>}{packagesLoading ? <p className="portfolio-feedback">Loading packages...</p> : error ? <div className="portfolio-feedback error"><p>{error}</p><button type="button" onClick={onRetry}>Try again</button></div> : packages.length === 0 ? <div className="portfolio-empty"><h3>No packages created yet.</h3><p>Create your first photography package.</p></div> : filtered.length === 0 ? <div className="portfolio-empty">No packages match your search or filters.</div> : <div className="services-grid packages-grid">{filtered.map((item) => <Card className="service-card package-card" key={item.id}>{item.coverImageUrl ? <img className="package-cover" src={resolvePackageImageUrl(item.coverImageUrl)} alt="" /> : <div className="package-cover package-cover-empty">No cover image</div>}<span className={`package-status ${item.status.toLowerCase()}`}>{item.status}</span><h3>{item.name}</h3><p>{item.description || "No description provided."}</p><strong className="package-price">{money.format(item.basePrice)}</strong><Facts item={item} /><div className="package-included"><strong>Included Services</strong><IncludedServices services={item.services} compact /></div><div className="package-included package-card-addons"><strong>Add-ons</strong>{item.addons?.length ? <ul className="package-service-list">{item.addons.slice(0, 3).map((addon) => <li key={addon.id}>{addon.name} — {money.format(addon.price)}</li>)}{item.addons.length > 3 && <li>+ {item.addons.length - 3} more</li>}</ul> : <p className="package-no-services">No add-ons</p>}</div><div className="package-actions"><button type="button" onClick={() => setViewing(item)}>View</button><button type="button" onClick={() => openEditor(item)}>Edit</button><button type="button" onClick={() => loadAddons(item)}>Add-ons</button><button type="button" className="danger-action" onClick={() => setDeleting(item)}>Delete</button></div></Card>)}</div>}
  {editor !== undefined && <Modal title={editor ? "Edit package" : "Add package"}><form className="package-editor" onSubmit={submit}>{field("name", "Package name", "text", { required: true, maxLength: 160 })}<label className="profile-field"><span>Description</span><textarea value={form.description} onChange={(event) => update("description", event.target.value)} maxLength={2000} /></label><div className="package-form-grid">{field("basePrice", "Base price (LKR)", "number", { min: "0.01", step: "0.01" })}{field("extraHourRate", "Extra hour rate (LKR)", "number", { min: "0", step: "0.01" })}{field("additionalPhotographerRate", "Additional photographer rate (LKR)", "number", { min: "0", step: "0.01" })}{field("durationHours", "Duration hours", "number", { min: "0.01", step: "0.01" })}{field("numberOfPhotographers", "Number of photographers", "number", { min: "1", step: "1" })}{field("editedPhotoCount", "Edited photo count", "number", { min: "0", step: "1" })}</div><fieldset className="package-services-fieldset"><legend>Included Services *</legend>{servicePicker}{validation.serviceIds && <small className="field-error">{validation.serviceIds}</small>}</fieldset><div className="package-options"><label><input type="checkbox" checked={form.albumIncluded} onChange={(event) => update("albumIncluded", event.target.checked)} /> Album included</label><label><input type="checkbox" checked={form.videoIncluded} onChange={(event) => update("videoIncluded", event.target.checked)} /> Video included</label></div><label className="profile-field"><span>Status</span><select value={form.status} onChange={(event) => update("status", event.target.value)}><option>Active</option><option>Inactive</option></select></label><label className="profile-field"><span>Cover image</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => update("coverImage", event.target.files?.[0] || null)} /></label><div className="studio-modal-actions"><button type="button" onClick={() => setEditor(undefined)}>Cancel</button><Button type="submit" disabled={saving}>{saving ? "Saving..." : editor ? "Update package" : "Create package"}</Button></div></form></Modal>}
  {viewing && <Modal title={viewing.name} className="package-view-modal"><p>{viewing.description || "No description provided."}</p><strong className="package-price">{money.format(viewing.basePrice)}</strong><Facts item={viewing} /><div className="package-included"><strong>Included Services</strong><IncludedServices services={viewing.services} /></div><div className="package-included"><strong>Available Add-ons</strong><AddonList addons={viewing.addons || []} onEdit={() => loadAddons(viewing)} onDelete={() => loadAddons(viewing)} /></div><div className="package-pricing-rules"><strong>Pricing Rules</strong><p>Extra hour rate: {money.format(viewing.extraHourRate || 0)}</p><p>Additional photographer rate: {money.format(viewing.additionalPhotographerRate || 0)}</p></div><div className="studio-modal-actions"><button type="button" onClick={() => setViewing(null)}>Close</button><Button onClick={() => { setViewing(null); openEditor(viewing); }}>Edit</Button></div></Modal>}
  {addonPanel && <Modal title={`${addonPanel.name} Add-ons`} className="package-view-modal">{addonsLoading ? <p className="package-picker-message">Loading add-ons...</p> : addonError && <p className="field-error">{addonError}</p>}<AddonList addons={addons} onEdit={(addon) => { setAddonEditor(addon); setAddonForm({ name: addon.name, description: addon.description, price: addon.price }); }} onDelete={setAddonDeleting} /><form onSubmit={saveAddon} className="addon-form"><label className="profile-field"><span>Name *</span><input value={addonForm.name} onChange={(event) => setAddonForm((current) => ({ ...current, name: event.target.value }))} maxLength={160} required /></label><label className="profile-field"><span>Description</span><textarea value={addonForm.description} onChange={(event) => setAddonForm((current) => ({ ...current, description: event.target.value }))} maxLength={1000} /></label><label className="profile-field"><span>Price (LKR) *</span><input type="number" min="0" step="0.01" value={addonForm.price} onChange={(event) => setAddonForm((current) => ({ ...current, price: event.target.value }))} required /></label><div className="studio-modal-actions"><button type="button" onClick={closeAddons}>Close</button><Button type="submit" disabled={addonSaving || addonsLoading}>{addonSaving ? "Saving..." : addonEditor ? "Update add-on" : "Add add-on"}</Button></div></form></Modal>}
    {deleting && <Modal title="Delete package" className="delete-package-dialog"><p>Delete <strong>{deleting.name}</strong>? Its add-ons and included-service links will be removed.</p><div className="studio-modal-actions"><button type="button" onClick={() => setDeleting(null)}>Cancel</button><button type="button" className="danger-button" onClick={async () => { await onDelete(deleting.id); setDeleting(null); }}>Delete package</button></div></Modal>}
    {addonDeleting && <Modal title="Delete add-on" className="delete-package-dialog"><p>Are you sure you want to delete this add-on?</p><div className="studio-modal-actions"><button type="button" onClick={() => setAddonDeleting(null)}>Cancel</button><button type="button" className="danger-button" onClick={deleteAddon}>Delete add-on</button></div></Modal>}
  </section>;
}
