using System.Text;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using PhotographyBooking.Api.Data;

var builder = WebApplication.CreateBuilder(args);

// Database
builder.Services.AddDbContext<ApplicationDbContext>(options =>
    options.UseNpgsql(
        builder.Configuration.GetConnectionString("DefaultConnection")
    ));

// Controllers
builder.Services.AddControllers();
builder.Services.AddScoped<PhotographyBooking.Api.Services.StudioService>();
builder.Services.AddScoped<PhotographyBooking.Api.Services.StudioPortfolioService>();
builder.Services.AddScoped<PhotographyBooking.Api.Services.StudioServicesCrudService>();
builder.Services.AddScoped<PhotographyBooking.Api.Services.StudioAvailabilityService>();
builder.Services.AddScoped<PhotographyBooking.Api.Services.PhotographyPackageService>();
builder.Services.AddScoped<PhotographyBooking.Api.Services.PackageAddonService>();
builder.Services.AddScoped<PhotographyBooking.Api.Services.PackagePriceCalculationService>();
var jwtSection = builder.Configuration.GetSection("Jwt");
var jwtKey = jwtSection["Key"] ?? throw new InvalidOperationException("Jwt:Key is required.");
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(options => options.TokenValidationParameters = new TokenValidationParameters
{
    ValidateIssuer = true, ValidIssuer = jwtSection["Issuer"], ValidateAudience = true, ValidAudience = jwtSection["Audience"],
    ValidateIssuerSigningKey = true, IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtKey)), ValidateLifetime = true, ClockSkew = TimeSpan.FromMinutes(1)
});

// Swagger
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

if (builder.Environment.IsDevelopment())
{
    builder.Services.AddCors(options => options.AddPolicy("FlutterDevelopment", policy =>
        policy.WithOrigins("http://localhost:5174").WithMethods("GET").AllowAnyHeader()));
}

var app = builder.Build();

using (var scope = app.Services.CreateScope())
{
    var dbContext = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();
    dbContext.Database.EnsureCreated();
    dbContext.Database.ExecuteSqlRaw(
        """
        CREATE TABLE IF NOT EXISTS "Users" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "FullName" text NOT NULL,
            "Email" text NOT NULL,
            "PasswordHash" text NOT NULL,
            "Role" text NOT NULL,
            "CreatedAt" timestamp with time zone NOT NULL
        );

        CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Email"
        ON "Users" ("Email");

        ALTER TABLE "Studios" ADD COLUMN IF NOT EXISTS "UserId" integer;
        ALTER TABLE "Studios" ADD COLUMN IF NOT EXISTS "StudioName" character varying(120) NOT NULL DEFAULT '';
        ALTER TABLE "Studios" ADD COLUMN IF NOT EXISTS "Description" character varying(1000) NOT NULL DEFAULT '';
        ALTER TABLE "Studios" ADD COLUMN IF NOT EXISTS "Location" character varying(160) NOT NULL DEFAULT '';
        ALTER TABLE "Studios" ADD COLUMN IF NOT EXISTS "Address" character varying(240) NOT NULL DEFAULT '';
        ALTER TABLE "Studios" ADD COLUMN IF NOT EXISTS "ContactNumber" character varying(30) NOT NULL DEFAULT '';
        ALTER TABLE "Studios" ADD COLUMN IF NOT EXISTS "Email" character varying(254) NOT NULL DEFAULT '';
        ALTER TABLE "Studios" ADD COLUMN IF NOT EXISTS "ExperienceYears" integer NOT NULL DEFAULT 0;
        ALTER TABLE "Studios" ADD COLUMN IF NOT EXISTS "PhotographyTypes" character varying(500) NOT NULL DEFAULT '';
        ALTER TABLE "Studios" ADD COLUMN IF NOT EXISTS "StartingPrice" numeric(12,2) NOT NULL DEFAULT 0;
        ALTER TABLE "Studios" ADD COLUMN IF NOT EXISTS "LogoUrl" character varying(2048) NOT NULL DEFAULT '';
        ALTER TABLE "Studios" ADD COLUMN IF NOT EXISTS "CoverPhotoUrl" character varying(2048) NOT NULL DEFAULT '';
        ALTER TABLE "Studios" ADD COLUMN IF NOT EXISTS "ProfileImage" character varying(2048) NOT NULL DEFAULT '';
        UPDATE "Studios" SET "LogoUrl" = "ProfileImage" WHERE "LogoUrl" = '' AND "ProfileImage" <> '';
        CREATE UNIQUE INDEX IF NOT EXISTS "IX_Studios_UserId" ON "Studios" ("UserId") WHERE "UserId" IS NOT NULL;

        CREATE TABLE IF NOT EXISTS "StudioPortfolios" ("Id" uuid PRIMARY KEY);
        ALTER TABLE "StudioPortfolios" ADD COLUMN IF NOT EXISTS "StudioId" uuid;
        ALTER TABLE "StudioPortfolios" ADD COLUMN IF NOT EXISTS "Title" character varying(160) NOT NULL DEFAULT '';
        ALTER TABLE "StudioPortfolios" ADD COLUMN IF NOT EXISTS "Description" character varying(1000) NOT NULL DEFAULT '';
        ALTER TABLE "StudioPortfolios" ADD COLUMN IF NOT EXISTS "ImageUrl" character varying(2048) NOT NULL DEFAULT '';
        ALTER TABLE "StudioPortfolios" ADD COLUMN IF NOT EXISTS "Category" character varying(60) NOT NULL DEFAULT '';
        ALTER TABLE "StudioPortfolios" ADD COLUMN IF NOT EXISTS "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;
        ALTER TABLE "StudioPortfolios" ADD COLUMN IF NOT EXISTS "UpdatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;
        CREATE INDEX IF NOT EXISTS "IX_StudioPortfolios_StudioId" ON "StudioPortfolios" ("StudioId");

        CREATE TABLE IF NOT EXISTS "StudioServices" ("Id" uuid PRIMARY KEY);
        ALTER TABLE "StudioServices" ADD COLUMN IF NOT EXISTS "StudioId" uuid;
        ALTER TABLE "StudioServices" ADD COLUMN IF NOT EXISTS "ServiceName" character varying(160) NOT NULL DEFAULT '';
        ALTER TABLE "StudioServices" ADD COLUMN IF NOT EXISTS "Description" character varying(1000) NOT NULL DEFAULT '';
        ALTER TABLE "StudioServices" ADD COLUMN IF NOT EXISTS "PackageDetails" text[] NOT NULL DEFAULT ARRAY[]::text[];
        ALTER TABLE "StudioServices" ADD COLUMN IF NOT EXISTS "StartingPrice" numeric(12,2) NOT NULL DEFAULT 0;
        CREATE INDEX IF NOT EXISTS "IX_StudioServices_StudioId" ON "StudioServices" ("StudioId");

        CREATE TABLE IF NOT EXISTS "StudioAvailabilities" ("Id" uuid PRIMARY KEY);
        ALTER TABLE "StudioAvailabilities" ADD COLUMN IF NOT EXISTS "StudioId" uuid;
        ALTER TABLE "StudioAvailabilities" ADD COLUMN IF NOT EXISTS "Date" date NOT NULL DEFAULT CURRENT_DATE;
        ALTER TABLE "StudioAvailabilities" ADD COLUMN IF NOT EXISTS "IsAvailable" boolean NOT NULL DEFAULT false;
        ALTER TABLE "StudioAvailabilities" ADD COLUMN IF NOT EXISTS "StartTime" time without time zone;
        ALTER TABLE "StudioAvailabilities" ADD COLUMN IF NOT EXISTS "EndTime" time without time zone;
        ALTER TABLE "StudioAvailabilities" ADD COLUMN IF NOT EXISTS "Notes" character varying(1000);
        CREATE UNIQUE INDEX IF NOT EXISTS "IX_StudioAvailabilities_StudioId_Date" ON "StudioAvailabilities" ("StudioId", "Date");

        CREATE TABLE IF NOT EXISTS "PhotographyPackages" (
            "Id" uuid PRIMARY KEY, "StudioId" uuid NOT NULL, "PackageName" character varying(160) NOT NULL,
            "Category" character varying(100) NOT NULL, "Description" character varying(2000) NOT NULL DEFAULT '',
            "Price" numeric(12,2) NOT NULL, "Duration" character varying(100) NOT NULL, "NumberOfPhotographers" integer NOT NULL,
            "CoverImageUrl" character varying(2048) NOT NULL DEFAULT '', "Status" character varying(20) NOT NULL,
            "CreatedAt" timestamp with time zone NOT NULL, "UpdatedAt" timestamp with time zone NOT NULL);
        ALTER TABLE "PhotographyPackages" ADD COLUMN IF NOT EXISTS "Name" character varying(160) NOT NULL DEFAULT '';
        ALTER TABLE "PhotographyPackages" ADD COLUMN IF NOT EXISTS "BasePrice" numeric(12,2) NOT NULL DEFAULT 0;
        ALTER TABLE "PhotographyPackages" ADD COLUMN IF NOT EXISTS "DurationHours" numeric(5,2) NOT NULL DEFAULT 0;
        ALTER TABLE "PhotographyPackages" ADD COLUMN IF NOT EXISTS "EditedPhotoCount" integer NOT NULL DEFAULT 0;
        ALTER TABLE "PhotographyPackages" ADD COLUMN IF NOT EXISTS "AlbumIncluded" boolean NOT NULL DEFAULT false;
        ALTER TABLE "PhotographyPackages" ADD COLUMN IF NOT EXISTS "VideoIncluded" boolean NOT NULL DEFAULT false;
        ALTER TABLE "PhotographyPackages" ADD COLUMN IF NOT EXISTS "ExtraHourRate" numeric(12,2) NOT NULL DEFAULT 0;
        ALTER TABLE "PhotographyPackages" ADD COLUMN IF NOT EXISTS "AdditionalPhotographerRate" numeric(12,2) NOT NULL DEFAULT 0;
        UPDATE "PhotographyPackages" SET "Name" = "PackageName" WHERE "Name" = '' AND "PackageName" <> '';
        UPDATE "PhotographyPackages" SET "BasePrice" = "Price" WHERE "BasePrice" = 0 AND "Price" <> 0;
        UPDATE "PhotographyPackages" SET "DurationHours" = NULLIF(regexp_replace("Duration", '[^0-9.]', '', 'g'), '')::numeric WHERE "DurationHours" = 0 AND "Duration" ~ '[0-9]';
        CREATE INDEX IF NOT EXISTS "IX_PhotographyPackages_StudioId" ON "PhotographyPackages" ("StudioId");
        CREATE TABLE IF NOT EXISTS "PackageAddons" (
            "Id" uuid PRIMARY KEY, "PackageId" uuid NOT NULL, "Name" character varying(160) NOT NULL,
            "Description" character varying(1000) NOT NULL DEFAULT '', "Price" numeric(12,2) NOT NULL,
            "CreatedAt" timestamp with time zone NOT NULL, "UpdatedAt" timestamp with time zone NOT NULL,
            CONSTRAINT "FK_PackageAddons_PhotographyPackages_PackageId" FOREIGN KEY ("PackageId") REFERENCES "PhotographyPackages" ("Id") ON DELETE CASCADE);
        CREATE INDEX IF NOT EXISTS "IX_PackageAddons_PackageId" ON "PackageAddons" ("PackageId");
        CREATE TABLE IF NOT EXISTS "PhotographyPackageServices" (
            "PhotographyPackageId" uuid NOT NULL, "StudioServiceId" uuid NOT NULL,
            PRIMARY KEY ("PhotographyPackageId", "StudioServiceId"));
        """);
}

// Development
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

if (!app.Environment.IsDevelopment())
{
    app.UseHttpsRedirection();
}

if (app.Environment.IsDevelopment())
{
    app.UseCors("FlutterDevelopment");
}

app.UseAuthentication();
app.UseAuthorization();
app.UseStaticFiles();

app.MapControllers();

app.Run();
