CREATE TABLE "BookingMessages"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "BookingId" integer NOT NULL,
    "SenderUserId" integer NOT NULL,
    "Message" character varying(1000) NOT NULL,
    "SentAt" timestamp with time zone NOT NULL,

    CONSTRAINT "FK_BookingMessages_Bookings_BookingId"
        FOREIGN KEY ("BookingId")
        REFERENCES "Bookings" ("Id")
        ON DELETE CASCADE,

    CONSTRAINT "FK_BookingMessages_Users_SenderUserId"
        FOREIGN KEY ("SenderUserId")
        REFERENCES "Users" ("Id")
        ON DELETE RESTRICT
);

CREATE INDEX "IX_BookingMessages_BookingId_SentAt"
    ON "BookingMessages" ("BookingId", "SentAt");
